# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  main.show-banner: false

logging:
  file: app.log
  level.gamesys.cashier.paymentslobbyservice: INFO
  pattern:
    console: "%-5level [%d{ISO8601, UTC}] [requestId=%X{Request-Tracker:-NA}] %logger: %msg%n"
    file: "%-5level [%d{ISO8601, UTC}] [requestId=%X{Request-Tracker:-NA}] %logger: %msg%n"
server:
  port: 9009

placeholderclient:
  hostURL: "http://jsonplaceholder.typicode.com"
  port: 80
  timeout: 120
  retries: 5
resourcemap:
  todoURI: "/todos/"
  commentURI: "/comments/"
  userURI: "/users/"

